#!/usr/bin/python
# $Id: run,v 1.9 2007/03/13 06:20:11 ping Exp $

import Ballot, verifier, Audio, Video, Printer, Navigator, pygame

AUDIO_DONE = pygame.USEREVENT
TIMER_DONE = pygame.USEREVENT + 1

ballot = Ballot.Ballot(open("ballot"))
verifier.verify(ballot)
audio = Audio.Audio(ballot.audio)
video = Video.Video(ballot.video)
printer = Printer.Printer(ballot.text)
navigator = Navigator.Navigator(ballot.model, audio, video, printer)

while 1:
    pygame.display.update()
    event = pygame.event.wait()
    if event.type == AUDIO_DONE:
        audio.next()
    if event.type == TIMER_DONE and not audio.playing:
        navigator.timeout()
    if event.type == pygame.MOUSEBUTTONDOWN:
        target_i = video.locate(*event.pos)
        if target_i != None:
            navigator.touch(target_i)
    if event.type == pygame.KEYDOWN:
        navigator.press(event.key)
    pygame.time.set_timer(TIMER_DONE, ballot.model.timeout_ms)
